version: "3.7"
services:

  catalog_db:
    container_name: catalog_db
    ports:
      - "1433:1433"
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - my_network
    env_file:
      - containers/db/db.env
      
networks:
  my_network:
    driver: bridge